file <- paste(getwd(), "/household_power_consumption.txt", sep = "")
data <- read.table(file, header = FALSE, sep = ";", skip = 66637, nrows = 2880)
colnames(data) <- c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
library(dplyr)
data <- mutate(data, DateTime = paste(Date, Time))
data <- select(data, DateTime, Global_active_power:Sub_metering_3)
hist(data$Global_active_power, col = "red", xlab = "Global Active Power (kilowatts)", ylab = "Frequency", main = "Global Active Power")
dev.copy(png, file = "plot1.png", width = 480, height = 480)
dev.off()